before_install: sudo apt-get install libzmq3-dev
script: bundle exec rspec
language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
